### ISSUE TITLE
Tags for Slabs and Planks arent added automatically. 

### ISSUE THREAD

**Issue by SaphieNyako** [ModdingX/LibX#35]
I have to add the Tags for minecraft PLANKS tag and WOODEN_SLABS otherwise they won't be added. 
I'm not sure about WOODEN_FENCES and WOODEN_STAIRS. But not tags are provided for these either if I dont add the tags myself.

**Comment by noeppi-noeppi** [comment]
Clarification: `PLANKS` was never meant to be set automatically by LibX.

Also it is worth noticing that LibX adds these blocks to tags named `libx:impl_wooden_fences` or `libx:impl_wooden_stairs`. Then the whole tag is added to the matching vanilla tag by LibX. This is due to the nature of the `CommonTagsProvider` as it needs to copy the tags when the sub-blocks from `DecoratedBlocks` are added but copying a tag twice or adding stuff without a `BlockItem` in the same provider to the same tag would fail.

It was fixed now, that the method that determines whether a block is a wood block did not consider the block material.
